>Superstore Dataset

1.Reading Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving archive (1).zip to archive (1).zip

In [3]:
import zipfile

with zipfile.ZipFile("archive (1).zip") as z:
    print(z.namelist())

['Sample - Superstore.csv']

In [4]:
df = pd.read_csv("archive (1).zip",
                 compression='zip',
                 encoding='latin1')

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [6]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [7]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

2.Cleaning Data

In [8]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [9]:
numericcolumns = ["Sales", "Profit", "Quantity", "Discount"]
for col in numericcolumns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [10]:
print(df.select_dtypes(include='number').dtypes)

Row ID           int64
Postal Code      int64
Sales          float64
Quantity         int64
Discount       float64
Profit         float64
dtype: object

In [11]:
df=df[df["Sales"] >= 0]
df=df[df["Quantity"] >= 0]

In [12]:
df = df[(df["Discount"] >= 0) & (df["Discount"] <= 1)]

In [13]:
df.duplicated().sum()

np.int64(0)

3.Exploring Data

In [14]:
df.shape

(9994, 21)

In [15]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [16]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [18]:
df.nunique()

Row ID           9994
Order ID         5009
Order Date       1237
Ship Date        1334
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              531
State              49
Postal Code       631
Region              4
Product ID       1862
Category            3
Sub-Category       17
Product Name     1850
Sales            5825
Quantity           14
Discount           12
Profit           7287
dtype: int64

3.1 Feature Extraction

In [19]:
df["Ship Date"]=pd.to_datetime(df["Ship Date"])

In [20]:
df["Year"]=df["Ship Date"].dt.year

In [21]:
df["Month"]=df["Ship Date"].dt.month

In [22]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Year',
       'Month'],
      dtype='object')

In [23]:
df['Unit_Price'] = np.random.uniform(10, 100, len(df))

In [24]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Unit_Price
0,1,CA-2016-152156,11/8/2016,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,93.590519
1,2,CA-2016-152156,11/8/2016,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,22.342055
2,3,CA-2016-138688,6/12/2016,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,70.068197
3,4,US-2015-108966,10/11/2015,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,80.112692
4,5,US-2015-108966,10/11/2015,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,88.527419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2014,1,10.320888
9990,9991,CA-2017-121258,2/26/2017,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,2017,3,71.095169
9991,9992,CA-2017-121258,2/26/2017,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,2017,3,18.184727
9992,9993,CA-2017-121258,2/26/2017,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,2017,3,73.479758
9993,9994,CA-2017-119914,5/4/2017,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,2017,5,76.570260

In [25]:
df['Total_Revenue']= df['Quantity']*df['Unit_Price']
print(df)

      Row ID        Order ID  Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156   11/8/2016 2016-11-11    Second Class
1          2  CA-2016-152156   11/8/2016 2016-11-11    Second Class
2          3  CA-2016-138688   6/12/2016 2016-06-16    Second Class
3          4  US-2015-108966  10/11/2015 2015-10-18  Standard Class
4          5  US-2015-108966  10/11/2015 2015-10-18  Standard Class
...      ...             ...         ...        ...             ...
9989    9990  CA-2014-110422   1/21/2014 2014-01-23    Second Class
9990    9991  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9991    9992  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9992    9993  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9993    9994  CA-2017-119914    5/4/2017 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... Sub-Category                                       Product Name  \
0     ...    Bookcases                  Bush Somerset Collection Bookcase
1     ...       Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
2     ...       Labels  Self-Adhesive Address Labels for Typewriters b...
3     ...       Tables      Bretford CR4500 Series Slim Rectangular Table
4     ...      Storage                     Eldon Fold 'N Roll Cart System
...   ...          ...                                                ...
9989  ...  Furnishings                             Ultra Door Pull Handle
9990  ...  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...
9991  ...       Phones                              Aastra 57i VoIP phone
9992  ...        Paper  It's Hot Message Books with Stickers, 2 3/4" x 5"
9993  ...   Appliances  Acco 7-Outlet Masterpiece Power Center, Wihtou...

         Sales Quantity Discount    Profit  Year  Month  Unit_Price  \
0     261.9600        2     0.00   41.9136  2016     11   93.590519
1     731.9400        3     0.00  219.5820  2016     11   22.342055
2      14.6200        2     0.00    6.8714  2016      6   70.068197
3     957.5775        5     0.45 -383.0310  2015     10   80.112692
4      22.3680        2     0.20    2.5164  2015     10   88.527419
...        ...      ...      ...       ...   ...    ...         ...
9989   25.2480        3     0.20    4.1028  2014      1   10.320888
9990   91.9600        2     0.00   15.6332  2017      3   71.095169
9991  258.5760        2     0.20   19.3932  2017      3   18.184727
9992   29.6000        4     0.00   13.3200  2017      3   73.479758
9993  243.1600        2     0.00   72.9480  2017      5   76.570260

      Total_Revenue
0        187.181037
1         67.026165
2        140.136394
3        400.563461
4        177.054837
...             ...
9989      30.962665
9990     142.190337
9991      36.369454
9992     293.919033
9993     153.140520

[9994 rows x 25 columns]

In [26]:
df['Unit_cost']= np.random.uniform(10, 100, len(df))

In [27]:
df["Total Cost"]= df["Quantity"]*df["Unit_cost"]
print(df)

      Row ID        Order ID  Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156   11/8/2016 2016-11-11    Second Class
1          2  CA-2016-152156   11/8/2016 2016-11-11    Second Class
2          3  CA-2016-138688   6/12/2016 2016-06-16    Second Class
3          4  US-2015-108966  10/11/2015 2015-10-18  Standard Class
4          5  US-2015-108966  10/11/2015 2015-10-18  Standard Class
...      ...             ...         ...        ...             ...
9989    9990  CA-2014-110422   1/21/2014 2014-01-23    Second Class
9990    9991  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9991    9992  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9992    9993  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9993    9994  CA-2017-119914    5/4/2017 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ...     Sales  Quantity Discount    Profit  Year Month Unit_Price  \
0     ...  261.9600         2     0.00   41.9136  2016    11  93.590519
1     ...  731.9400         3     0.00  219.5820  2016    11  22.342055
2     ...   14.6200         2     0.00    6.8714  2016     6  70.068197
3     ...  957.5775         5     0.45 -383.0310  2015    10  80.112692
4     ...   22.3680         2     0.20    2.5164  2015    10  88.527419
...   ...       ...       ...      ...       ...   ...   ...        ...
9989  ...   25.2480         3     0.20    4.1028  2014     1  10.320888
9990  ...   91.9600         2     0.00   15.6332  2017     3  71.095169
9991  ...  258.5760         2     0.20   19.3932  2017     3  18.184727
9992  ...   29.6000         4     0.00   13.3200  2017     3  73.479758
9993  ...  243.1600         2     0.00   72.9480  2017     5  76.570260

      Total_Revenue  Unit_cost  Total Cost
0        187.181037  83.365426  166.730853
1         67.026165  49.604456  148.813368
2        140.136394  34.261521   68.523043
3        400.563461  72.968886  364.844428
4        177.054837  47.302380   94.604760
...             ...        ...         ...
9989      30.962665  38.991352  116.974057
9990     142.190337  74.818640  149.637280
9991      36.369454  16.289102   32.578204
9992     293.919033  40.681108  162.724431
9993     153.140520  73.831774  147.663547

[9994 rows x 27 columns]

In [28]:
df["Profit"]= df["Total_Revenue"]- df["Total Cost"]
print(df)

      Row ID        Order ID  Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156   11/8/2016 2016-11-11    Second Class
1          2  CA-2016-152156   11/8/2016 2016-11-11    Second Class
2          3  CA-2016-138688   6/12/2016 2016-06-16    Second Class
3          4  US-2015-108966  10/11/2015 2015-10-18  Standard Class
4          5  US-2015-108966  10/11/2015 2015-10-18  Standard Class
...      ...             ...         ...        ...             ...
9989    9990  CA-2014-110422   1/21/2014 2014-01-23    Second Class
9990    9991  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9991    9992  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9992    9993  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9993    9994  CA-2017-119914    5/4/2017 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ...     Sales  Quantity Discount      Profit  Year Month Unit_Price  \
0     ...  261.9600         2     0.00   20.450184  2016    11  93.590519
1     ...  731.9400         3     0.00  -81.787203  2016    11  22.342055
2     ...   14.6200         2     0.00   71.613351  2016     6  70.068197
3     ...  957.5775         5     0.45   35.719034  2015    10  80.112692
4     ...   22.3680         2     0.20   82.450077  2015    10  88.527419
...   ...       ...       ...      ...         ...   ...   ...        ...
9989  ...   25.2480         3     0.20  -86.011392  2014     1  10.320888
9990  ...   91.9600         2     0.00   -7.446943  2017     3  71.095169
9991  ...  258.5760         2     0.20    3.791250  2017     3  18.184727
9992  ...   29.6000         4     0.00  131.194602  2017     3  73.479758
9993  ...  243.1600         2     0.00    5.476972  2017     5  76.570260

      Total_Revenue  Unit_cost  Total Cost
0        187.181037  83.365426  166.730853
1         67.026165  49.604456  148.813368
2        140.136394  34.261521   68.523043
3        400.563461  72.968886  364.844428
4        177.054837  47.302380   94.604760
...             ...        ...         ...
9989      30.962665  38.991352  116.974057
9990     142.190337  74.818640  149.637280
9991      36.369454  16.289102   32.578204
9992     293.919033  40.681108  162.724431
9993     153.140520  73.831774  147.663547

[9994 rows x 27 columns]

In [29]:
def clas_profit(x):
    if x > 0:
        return"Positive"
    elif x < 0:
        return"Negative"
    else:
        return"Break Even"
df["ProfitStatus"] = df["Profit"].apply(clas_profit)
print(df)

      Row ID        Order ID  Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156   11/8/2016 2016-11-11    Second Class
1          2  CA-2016-152156   11/8/2016 2016-11-11    Second Class
2          3  CA-2016-138688   6/12/2016 2016-06-16    Second Class
3          4  US-2015-108966  10/11/2015 2015-10-18  Standard Class
4          5  US-2015-108966  10/11/2015 2015-10-18  Standard Class
...      ...             ...         ...        ...             ...
9989    9990  CA-2014-110422   1/21/2014 2014-01-23    Second Class
9990    9991  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9991    9992  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9992    9993  CA-2017-121258   2/26/2017 2017-03-03  Standard Class
9993    9994  CA-2017-119914    5/4/2017 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... Quantity  Discount      Profit  Year Month Unit_Price Total_Revenue  \
0     ...        2      0.00   20.450184  2016    11  93.590519    187.181037
1     ...        3      0.00  -81.787203  2016    11  22.342055     67.026165
2     ...        2      0.00   71.613351  2016     6  70.068197    140.136394
3     ...        5      0.45   35.719034  2015    10  80.112692    400.563461
4     ...        2      0.20   82.450077  2015    10  88.527419    177.054837
...   ...      ...       ...         ...   ...   ...        ...           ...
9989  ...        3      0.20  -86.011392  2014     1  10.320888     30.962665
9990  ...        2      0.00   -7.446943  2017     3  71.095169    142.190337
9991  ...        2      0.20    3.791250  2017     3  18.184727     36.369454
9992  ...        4      0.00  131.194602  2017     3  73.479758    293.919033
9993  ...        2      0.00    5.476972  2017     5  76.570260    153.140520

      Unit_cost  Total Cost  ProfitStatus
0     83.365426  166.730853      Positive
1     49.604456  148.813368      Negative
2     34.261521   68.523043      Positive
3     72.968886  364.844428      Positive
4     47.302380   94.604760      Positive
...         ...         ...           ...
9989  38.991352  116.974057      Negative
9990  74.818640  149.637280      Negative
9991  16.289102   32.578204      Positive
9992  40.681108  162.724431      Positive
9993  73.831774  147.663547      Positive

[9994 rows x 28 columns]

3.2 Data Analysis Using the Following Questions

In [30]:
#question 1
print(len(df))

9994

In [31]:
#question 2
print(df["Total_Revenue"].sum())

2076381.320493091

In [32]:
#question 3
print(df["Unit_Price"].mean())

54.626848001496064

In [33]:
#question 4
print(df.groupby("Sub-Category")["Total_Revenue"].sum().sort_values(ascending=False))

Sub-Category
Binders        325581.081862
Paper          286420.988138
Furnishings    199803.573723
Phones         175159.410336
Storage        170942.206328
Art            163778.442911
Accessories    161140.078607
Chairs         129583.324226
Appliances      97733.826331
Labels          76254.827357
Tables          71361.832517
Fasteners       50624.999704
Envelopes       50483.737366
Bookcases       47521.396387
Supplies        34350.909054
Machines        22978.001554
Copiers         12662.684092
Name: Total_Revenue, dtype: float64

In [34]:
#question 5
print(df["Profit"].max())

1106.0002693450192

In [35]:
#question 6
print(df.groupby("State")["Total_Revenue"].sum().sort_values(ascending=False))

State
California              424794.884639
New York                236569.628679
Texas                   200277.262925
Pennsylvania            117049.531778
Washington              104061.905047
Illinois                 98763.372707
Ohio                     92086.880280
Florida                  75416.827593
North Carolina           55601.813228
Michigan                 51820.845207
Arizona                  51261.316737
Virginia                 51060.365423
Georgia                  38430.901290
Tennessee                37121.081668
Colorado                 35879.372266
Indiana                  30395.562372
Kentucky                 29267.660337
Oregon                   28038.783587
Massachusetts            27578.172077
Wisconsin                25142.736001
New Jersey               24589.789206
Maryland                 22929.509233
Delaware                 20198.729638
Minnesota                16412.538825
Alabama                  15449.201693
Connecticut              14247.691548
Oklahoma                 13289.246556
Arkansas                 13083.526738
Missouri                 12772.329274
Rhode Island             12466.379826
Utah                     11644.986134
Mississippi              11630.661133
New Mexico                8980.827780
Louisiana                 8742.452049
South Carolina            8563.849594
Nebraska                  7660.839952
Nevada                    6995.047228
New Hampshire             6363.194663
Iowa                      5757.703798
Kansas                    4615.802836
Montana                   3695.577576
Idaho                     3538.056424
Maine                     2735.807559
South Dakota              2573.323426
North Dakota              2258.232192
Vermont                   1891.316472
District of Columbia      1788.564253
West Virginia              819.920693
Wyoming                     67.310358
Name: Total_Revenue, dtype: float64

In [36]:
#question 7
print(df["Year"].value_counts())

Year
2017    3303
2016    2578
2015    2131
2014    1940
2018      42
Name: count, dtype: int64

In [37]:
#question 8
print(df["Category"].value_counts())

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [38]:
#question 9
print(df.groupby(["Month","Category"])["Profit"].sum())

Month  Category
1      Furniture         -1049.376362
       Office Supplies   -2629.363933
       Technology          720.439529
2      Furniture           627.910609
       Office Supplies    1064.095411
       Technology           85.382077
3      Furniture         -2615.171847
       Office Supplies    -660.765297
       Technology          631.739648
4      Furniture          1158.692544
       Office Supplies    2634.435015
       Technology         1551.562128
5      Furniture          1485.013324
       Office Supplies    1818.205091
       Technology        -1093.402562
6      Furniture          3721.587673
       Office Supplies     -21.878593
       Technology        -1134.659134
7      Furniture          4868.142544
       Office Supplies    4922.350929
       Technology          -36.738248
8      Furniture           662.037775
       Office Supplies   -5963.721009
       Technology          869.171731
9      Furniture         -2335.431348
       Office Supplies   -1188.067967
       Technology        -4647.054638
10     Furniture          4654.889708
       Office Supplies     362.728264
       Technology         1051.441758
11     Furniture          2210.758832
       Office Supplies    3194.472433
       Technology          839.225944
12     Furniture         -4181.098993
       Office Supplies   -2607.029775
       Technology        -2405.931705
Name: Profit, dtype: float64

In [39]:
#question 10
print(df.groupby("Month")["Total_Revenue"].sum().sort_values(ascending=False))

Month
11    311771.726901
12    291151.786043
9     270586.148304
10    174496.320405
7     157683.825653
6     156837.977223
5     141065.198874
8     140766.167637
4     134862.824978
3     130172.658223
1     103399.235503
2      63587.450750
Name: Total_Revenue, dtype: float64